name: Deploy to Multiple Environments

on:
  push:
    branches:
      - master

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://staging.example.com
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Staging
        run: echo "Deploying to the staging environment..."

  deploy-production:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://production.example.com
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Production
        run: echo "Deploying to the production environment..."
