name: CI/CD Echo Pipeline

on:
  push:
    branches:
      - master
      - staging

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: echo "Checking out code..."
      - name: Build Application
        run: echo "Building application..."

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run Unit Tests
        run: echo "Running unit tests..."

  bdd_tests:
    name: BDD Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run BDD Tests
        run: echo "Running BDD tests..."

  security_tests:
    name: Security Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run Security Tests
        run: echo "Running security tests..."

  deploy_dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs:
      - unit_tests
      - bdd_tests
      - security_tests
    if: github.ref == 'refs/heads/dev'
    environment:
      name: dev
      url: https://dev.example.com
    steps:
      - name: Deploy to Dev
        run: echo "Deploying to Dev environment..."

  deploy_production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs:
      - unit_tests
      - bdd_tests
      - security_tests
    if: github.ref == 'refs/heads/master'
    environment:
      name: prod
      url: https://production.example.com
    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production environment..."
